use serde::Serialize;
use std::path::Path;

#[derive(Serialize, Clone)]
pub struct Example {
    pub id: String,
    pub name: String,
    pub category: String,
    pub description: String,
    pub code: String,
}

struct ExampleMeta {
    id: &'static str,
    name: &'static str,
    category: &'static str,
    description: &'static str,
    file: &'static str,
}

const REGISTRY: &[ExampleMeta] = &[
    // ── Getting Started ──
    ExampleMeta {
        id: "quickstart",
        name: "Quickstart",
        category: "Getting Started",
        description: "Basic LLM agent with Gemini — the simplest ADK program",
        file: "quickstart.rs",
    },
    ExampleMeta {
        id: "template",
        name: "Instruction Templates",
        category: "Getting Started",
        description: "Dynamic instructions with session state placeholders",
        file: "template.rs",
    },
    ExampleMeta {
        id: "structured_output",
        name: "Structured Output",
        category: "Getting Started",
        description: "Force JSON responses matching a schema",
        file: "structured_output.rs",
    },
    // ── Function Tools ──
    ExampleMeta {
        id: "function_tool",
        name: "Basic Function Tools",
        category: "Function Tools",
        description: "Agent with typed function tools and schema validation",
        file: "function_tool.rs",
    },
    ExampleMeta {
        id: "multi_tools",
        name: "Multiple Tools",
        category: "Function Tools",
        description: "Agent with weather, calculator, and unit converter tools",
        file: "multi_tools.rs",
    },
    ExampleMeta {
        id: "multi_turn",
        name: "Multi-Turn Conversation",
        category: "Function Tools",
        description: "Shopping assistant with cart — tool context preserved across 3 turns",
        file: "multi_turn.rs",
    },
    // ── Agents ──
    ExampleMeta {
        id: "agent_tool",
        name: "Agent-as-Tool",
        category: "Agents",
        description: "Wrap specialist agents as callable tools for a coordinator",
        file: "agent_tool.rs",
    },
    ExampleMeta {
        id: "customer_service",
        name: "Customer Service",
        category: "Agents",
        description: "Billing issue → agent escalation → manager approval — full resolution flow",
        file: "customer_service.rs",
    },
    ExampleMeta {
        id: "conditional_router",
        name: "LLM Conditional Router",
        category: "Agents",
        description: "LLM classifies queries and routes to specialist agents",
        file: "conditional_router.rs",
    },
    // ── Callbacks ──
    ExampleMeta {
        id: "callbacks_logging",
        name: "Logging Callbacks",
        category: "Callbacks",
        description: "Before/after callbacks for logging agent interactions",
        file: "callbacks_logging.rs",
    },
    ExampleMeta {
        id: "callbacks_guardrails",
        name: "Input Guardrails",
        category: "Callbacks",
        description: "Block inappropriate content with before_callback guardrails",
        file: "callbacks_guardrails.rs",
    },
    // ── Workflows ──
    ExampleMeta {
        id: "sequential",
        name: "Sequential Pipeline",
        category: "Workflows",
        description: "Chain agents in a multi-step pipeline (research → write → edit)",
        file: "sequential.rs",
    },
    ExampleMeta {
        id: "parallel",
        name: "Parallel Analysis",
        category: "Workflows",
        description: "Run multiple agents concurrently and merge results",
        file: "parallel.rs",
    },
    ExampleMeta {
        id: "loop_workflow",
        name: "Iterative Loop",
        category: "Workflows",
        description: "Refine content in a loop until quality threshold is met",
        file: "loop_workflow.rs",
    },
    // ── Graph ──
    ExampleMeta {
        id: "graph_workflow",
        name: "Graph Pipeline",
        category: "Graph",
        description: "Analyst → Writer → Editor agents in a sequential graph with deterministic data prep nodes",
        file: "graph_workflow.rs",
    },
    ExampleMeta {
        id: "graph_conditional",
        name: "Conditional Routing",
        category: "Graph",
        description: "LLM classifier routes support tickets to specialist agents via conditional edges",
        file: "graph_conditional.rs",
    },
    ExampleMeta {
        id: "react_pattern",
        name: "ReAct Pattern",
        category: "Graph",
        description: "Iterative reasoning with tools in a graph cycle",
        file: "react_pattern.rs",
    },
    ExampleMeta {
        id: "supervisor_routing",
        name: "Supervisor Routing",
        category: "Graph",
        description: "Supervisor delegates tasks to specialist agent nodes",
        file: "supervisor_routing.rs",
    },
    // ── Sessions & State ──
    ExampleMeta {
        id: "session_state",
        name: "Session & State",
        category: "Sessions",
        description: "Manage conversation sessions with Runner and state",
        file: "session_state.rs",
    },
    ExampleMeta {
        id: "postgres_sessions",
        name: "PostgreSQL Sessions",
        category: "Sessions",
        description: "ACID-compliant session persistence with PostgreSQL — three-tier state, JSONB, advisory-lock migrations",
        file: "postgres_sessions.rs",
    },
    ExampleMeta {
        id: "mongodb_sessions",
        name: "MongoDB Sessions",
        category: "Sessions",
        description: "Schema-flexible document sessions with MongoDB — nested state, arrays, TTL indexes",
        file: "mongodb_sessions.rs",
    },
    ExampleMeta {
        id: "neo4j_sessions",
        name: "Neo4j Sessions",
        category: "Sessions",
        description: "Graph-powered session relationships with Neo4j — nodes, constraints, Cypher queries",
        file: "neo4j_sessions.rs",
    },
    // ── Model Providers ──
    ExampleMeta {
        id: "openai_quickstart",
        name: "OpenAI",
        category: "Providers",
        description: "Responses API — o4-mini reasoning with configurable effort + tool use",
        file: "openai_quickstart.rs",
    },
    ExampleMeta {
        id: "anthropic_quickstart",
        name: "Anthropic",
        category: "Providers",
        description: "Claude Sonnet 4.5 with extended thinking (10K budget) + code review",
        file: "anthropic_quickstart.rs",
    },
    ExampleMeta {
        id: "deepseek_quickstart",
        name: "DeepSeek",
        category: "Providers",
        description: "DeepSeek Reasoner with chain-of-thought for math & logic",
        file: "deepseek_quickstart.rs",
    },
    ExampleMeta {
        id: "mistral_quickstart",
        name: "Mistral",
        category: "Providers",
        description: "Mistral Medium — multilingual translation + sentiment tools",
        file: "mistral_quickstart.rs",
    },
    ExampleMeta {
        id: "xai_quickstart",
        name: "xAI (Grok)",
        category: "Providers",
        description: "Grok-3-mini-fast debugging assistant with tool use",
        file: "xai_quickstart.rs",
    },
    ExampleMeta {
        id: "azure_ai_quickstart",
        name: "Azure AI",
        category: "Providers",
        description: "Azure AI Inference endpoint — text classification + summarization with Llama/Mistral",
        file: "azure_ai_quickstart.rs",
    },
    ExampleMeta {
        id: "bedrock_quickstart",
        name: "AWS Bedrock",
        category: "Providers",
        description: "Amazon Bedrock with Claude — cloud architecture design + threat modeling via IAM auth",
        file: "bedrock_quickstart.rs",
    },
    ExampleMeta {
        id: "openrouter_quickstart",
        name: "OpenRouter",
        category: "Providers",
        description: "Multi-provider AI gateway — 200+ models with tool use, provider routing, and automatic fallback",
        file: "openrouter_quickstart.rs",
    },
    // ── Audio ──
    ExampleMeta {
        id: "poem_tts",
        name: "Poem → Speech",
        category: "Audio",
        description: "LLM writes a random poem, Gemini TTS synthesizes it to audio",
        file: "poem_tts.rs",
    },
    ExampleMeta {
        id: "realtime_audio",
        name: "Realtime Voice",
        category: "Audio",
        description: "OpenAI Realtime API — text prompt to expressive voice audio via WebSocket",
        file: "realtime_audio.rs",
    },
    ExampleMeta {
        id: "realtime_session_update",
        name: "Realtime Session Update",
        category: "Audio",
        description: "Mid-session persona switch — general assistant → travel agent with swapped tools, no reconnect",
        file: "realtime_session_update.rs",
    },
    ExampleMeta {
        id: "realtime_tools",
        name: "Realtime Tools",
        category: "Audio",
        description: "Function calling in voice — weather, calculator, and time tools over a single WebSocket",
        file: "realtime_tools.rs",
    },
    ExampleMeta {
        id: "gemini_live_tools",
        name: "Gemini Live Tools",
        category: "Audio",
        description: "Gemini Live voice agent with weather + time tools — native audio, tool call → response loop",
        file: "gemini_live_tools.rs",
    },
    ExampleMeta {
        id: "gemini_live_context",
        name: "Gemini Live Context Switch",
        category: "Audio",
        description: "Mid-session persona switch via session resumption — tech support → billing agent with swapped tools",
        file: "gemini_live_context.rs",
    },
    // ── Extensions ──
    ExampleMeta {
        id: "skill_discovery",
        name: "Skill Discovery",
        category: "Extensions",
        description: "Discover, parse, score, and inject agentskills.io skill files into prompts",
        file: "skill_discovery.rs",
    },
    ExampleMeta {
        id: "plugin_system",
        name: "Plugin System",
        category: "Extensions",
        description: "Lifecycle hooks for agents — message, model, tool, and run callbacks",
        file: "plugin_system.rs",
    },
    // ── Coding ──
    ExampleMeta {
        id: "code_execution",
        name: "Code Execution",
        category: "Coding",
        description: "Typed sandbox with truthful capability model — policy validation and CodeTool",
        file: "code_execution.rs",
    },
    ExampleMeta {
        id: "cli_launcher",
        name: "CLI Launcher",
        category: "Coding",
        description: "Deploy agents as interactive REPL or HTTP server with streaming",
        file: "cli_launcher.rs",
    },
    // ── RAG ──
    ExampleMeta {
        id: "rag_multi_collection",
        name: "Multi-Collection RAG",
        category: "RAG",
        description: "Domain-isolated knowledge bases with cross-collection search",
        file: "rag_multi_collection.rs",
    },
    ExampleMeta {
        id: "rag_custom_embedder",
        name: "Custom Embedder",
        category: "RAG",
        description: "Implement EmbeddingProvider trait — TF-IDF example with cosine similarity",
        file: "rag_custom_embedder.rs",
    },
    // ── Thinking ──
    ExampleMeta {
        id: "thinking_openai",
        name: "Reasoning Effort (OpenAI)",
        category: "Thinking",
        description: "Responses API with o4-mini — Low/Medium/High reasoning effort + detailed summaries",
        file: "thinking_openai.rs",
    },
    ExampleMeta {
        id: "thinking_anthropic",
        name: "Extended Thinking (Anthropic)",
        category: "Thinking",
        description: "Claude's internal reasoning with 10K token budget — deep systems design analysis",
        file: "thinking_anthropic.rs",
    },
    ExampleMeta {
        id: "thinking_deepseek",
        name: "Chain-of-Thought (DeepSeek)",
        category: "Thinking",
        description: "Visible chain-of-thought reasoning — watch the model think through math problems",
        file: "thinking_deepseek.rs",
    },
    ExampleMeta {
        id: "thinking_xai",
        name: "Grok Thinking (xAI)",
        category: "Thinking",
        description: "OpenAI-compatible reasoning — Grok-3-mini thinks through Fermi estimation with tools",
        file: "thinking_xai.rs",
    },
    ExampleMeta {
        id: "thinking_gemini",
        name: "Thought Signatures (Gemini)",
        category: "Thinking",
        description: "Native thinking traces + thought_signature on tool calls — multi-turn with preserved context",
        file: "thinking_gemini.rs",
    },
    // ── Advanced ──
    ExampleMeta {
        id: "artifact_agent",
        name: "Artifact Storage",
        category: "Advanced",
        description: "Agent with versioned file storage — save, load, and list artifacts mid-conversation",
        file: "artifact_agent.rs",
    },
    ExampleMeta {
        id: "memory_agent",
        name: "Long-Term Memory",
        category: "Advanced",
        description: "Cross-session memory recall — agent remembers past conversations and preferences",
        file: "memory_agent.rs",
    },
    ExampleMeta {
        id: "guardrails_advanced",
        name: "Advanced Guardrails",
        category: "Advanced",
        description: "PII redaction, content filtering, and GuardrailSet with LLM agent integration",
        file: "guardrails_advanced.rs",
    },
    ExampleMeta {
        id: "auth_rbac",
        name: "RBAC Access Control",
        category: "Advanced",
        description: "Role-based tool permissions — analyst can search but not delete, admin gets full access",
        file: "auth_rbac.rs",
    },
    // ── Security ──
    ExampleMeta {
        id: "auth_identity",
        name: "Typed Identity",
        category: "Security",
        description: "Injection-proof identity system — validated IDs, null-byte rejection, multi-tenant session isolation",
        file: "auth_identity.rs",
    },
    ExampleMeta {
        id: "auth_audit",
        name: "Audit Trail",
        category: "Security",
        description: "Tamper-evident access logging — RBAC permission matrix, AuditSink, AuthMiddleware tool protection",
        file: "auth_audit.rs",
    },
    ExampleMeta {
        id: "auth_sso",
        name: "SSO & JWT",
        category: "Security",
        description: "Enterprise identity — Google/Azure/Okta SSO, JWT validation, OIDC discovery, claims-to-RBAC mapping",
        file: "auth_sso.rs",
    },
    // ── Built-in Tools ──
    ExampleMeta {
        id: "builtin_gemini",
        name: "Google Search (Gemini)",
        category: "Built-in Tools",
        description: "GoogleSearchTool wrapper — server-side search, grounding metadata, and thought signatures across multi-turn tool use",
        file: "builtin_gemini.rs",
    },
    ExampleMeta {
        id: "builtin_anthropic",
        name: "Web Search (Anthropic)",
        category: "Built-in Tools",
        description: "WebSearchTool wrapper for Claude — server-side search with local function tools across multiple turns",
        file: "builtin_anthropic.rs",
    },
    ExampleMeta {
        id: "builtin_openai",
        name: "Web Search (OpenAI)",
        category: "Built-in Tools",
        description: "OpenAIWebSearchTool wrapper — hosted search with local function tools across multiple turns",
        file: "builtin_openai.rs",
    },
    // ── Payments ──
    ExampleMeta {
        id: "payments_checkout",
        name: "Checkout Agent",
        category: "Payments",
        description: "AI-driven checkout lifecycle — create session, select fulfillment, authorize payment, verify status with evidence trail",
        file: "payments_checkout.rs",
    },
    ExampleMeta {
        id: "payments_guardrails",
        name: "Payment Guardrails",
        category: "Payments",
        description: "Amount thresholds, merchant allowlists, policy sets, card/PII redaction, evidence references",
        file: "payments_guardrails.rs",
    },
    ExampleMeta {
        id: "payments_agent",
        name: "Shopping Agent",
        category: "Payments",
        description: "LLM agent with checkout tools — browse, cart, guardrail-enforced payment, masked transaction status",
        file: "payments_agent.rs",
    },
    // ── Action Nodes ──
    // ── Competitive ──
    ExampleMeta {
        id: "competitive_auto_provider",
        name: "Auto-Provider + Encryption",
        category: "Competitive",
        description: "provider_from_env() auto-detects API keys + EncryptedSession with AES-256-GCM at-rest encryption",
        file: "competitive_auto_provider.rs",
    },
    ExampleMeta {
        id: "competitive_graph_resume",
        name: "Durable Graph Resume",
        category: "Competitive",
        description: "MemoryCheckpointer saves graph state — resume from checkpoint after crash, skip completed nodes",
        file: "competitive_graph_resume.rs",
    },
    ExampleMeta {
        id: "competitive_tool_search",
        name: "Tool Search Filter",
        category: "Competitive",
        description: "ToolSearchConfig regex filtering — hide dangerous tools from the LLM while keeping them registered",
        file: "competitive_tool_search.rs",
    },
    // ── v0.7 / v0.8 Features ──
    ExampleMeta {
        id: "deepseek_v4_thinking",
        name: "DeepSeek V4 Thinking",
        category: "v0.7+ Features",
        description: "ThinkingMode, ReasoningEffort, strict tool mode — V4 Flash/Pro with visible chain-of-thought",
        file: "deepseek_v4_thinking.rs",
    },
    ExampleMeta {
        id: "project_scoped_memory",
        name: "Project-Scoped Memory",
        category: "v0.7+ Features",
        description: "project_id dimension isolates memories per project — same user, different projects, zero leakage",
        file: "project_scoped_memory.rs",
    },
    ExampleMeta {
        id: "bounded_execution",
        name: "Bounded Execution",
        category: "v0.7+ Features",
        description: "RunConfig with history_max_events and max_tool_concurrency — production safety bounds for agents",
        file: "bounded_execution.rs",
    },
    ExampleMeta {
        id: "awp_discovery",
        name: "AWP Agent Discovery",
        category: "v0.7+ Features",
        description: "Agentic Web Protocol — capability manifests, trust levels, rate limits, and agent-to-agent discovery",
        file: "awp_discovery.rs",
    },
    ExampleMeta {
        id: "minimal_agent",
        name: "Minimal Tier Agent",
        category: "v0.7+ Features",
        description: "Lightest possible agent using v0.8 minimal feature tier — 32% smaller builds, ~50s compile",
        file: "minimal_agent.rs",
    },
    // ── v0.8.1 / v0.8.2 Features ──
    ExampleMeta {
        id: "schema_normalization",
        name: "Schema Normalization",
        category: "v0.8+ Features",
        description: "Provider-aware MCP schema transforms — Gemini, OpenAI, Anthropic each normalize differently (no API keys)",
        file: "schema_normalization.rs",
    },
    ExampleMeta {
        id: "acp_server",
        name: "ACP Server",
        category: "v0.8+ Features",
        description: "Expose ADK agents via Agent Client Protocol — IDE connections (Kiro, VS Code, Claude Code)",
        file: "acp_server.rs",
    },
    ExampleMeta {
        id: "retry_reflect",
        name: "Retry & Reflect",
        category: "v0.8+ Features",
        description: "Plugin handles tool failures with exponential backoff and reflection prompts for self-correction",
        file: "retry_reflect.rs",
    },
    // ── Anthropic Features ──
    ExampleMeta {
        id: "anthropic_caching",
        name: "Prompt Caching",
        category: "Anthropic",
        description: "Multi-turn agent with prompt caching — cache creation (25% surcharge) then cache hit (90% discount)",
        file: "anthropic_caching.rs",
    },
    ExampleMeta {
        id: "anthropic_vision",
        name: "Vision Agent",
        category: "Anthropic",
        description: "Image analysis agent — Claude sees images via URL and logs structured observations with tools",
        file: "anthropic_vision.rs",
    },
    ExampleMeta {
        id: "anthropic_structured",
        name: "Structured Extraction",
        category: "Anthropic",
        description: "Typed JSON extraction from unstructured text — tool schema forces structured output",
        file: "anthropic_structured.rs",
    },
    ExampleMeta {
        id: "anthropic_streaming",
        name: "Streaming + Tools",
        category: "Anthropic",
        description: "Real-time streaming with mid-stream tool calls — time-to-first-token metrics",
        file: "anthropic_streaming.rs",
    },
    ExampleMeta {
        id: "anthropic_token_counting",
        name: "Token Counting & Models",
        category: "Anthropic",
        description: "Model discovery, pre-flight token counting, cost estimation, and rate limit info",
        file: "anthropic_token_counting.rs",
    },
    ExampleMeta {
        id: "anthropic_multi_tool",
        name: "Multi-Tool Agent",
        category: "Anthropic",
        description: "Travel assistant with weather, calculator, and unit converter — parallel tool orchestration",
        file: "anthropic_multi_tool.rs",
    },
    ExampleMeta {
        id: "anthropic_thinking_graph",
        name: "Thinking Graph",
        category: "Anthropic",
        description: "Extended thinking (10K budget) in a StateGraph — deep thinker → concise summarizer pipeline",
        file: "anthropic_thinking_graph.rs",
    },
    // ── Action Nodes ──
    ExampleMeta {
        id: "action_set_transform",
        name: "Data Enrichment",
        category: "Action Nodes",
        description: "SET + TRANSFORM action nodes prep data, then an LLM agent writes personalized outreach",
        file: "action_set_transform.rs",
    },
    ExampleMeta {
        id: "action_switch_loop",
        name: "Smart Ticket Router",
        category: "Action Nodes",
        description: "LLM classifier + deterministic SWITCH routing + specialist agents handle support tickets",
        file: "action_switch_loop.rs",
    },
    ExampleMeta {
        id: "action_workflow",
        name: "Content Pipeline",
        category: "Action Nodes",
        description: "SET → Research Agent → TRANSFORM → Writer Agent → SWITCH → Editor Agent — full content pipeline",
        file: "action_workflow.rs",
    },
    // ── A2A Protocol ──
    ExampleMeta {
        id: "a2a_quickstart",
        name: "A2A Quickstart",
        category: "A2A Protocol",
        description: "Agent-to-Agent protocol basics — expose and connect agents over HTTP",
        file: "a2a_quickstart.rs",
    },
    ExampleMeta {
        id: "a2a_interceptors",
        name: "A2A Interceptors",
        category: "A2A Protocol",
        description: "Request/response interceptors for A2A protocol — logging, auth, rate limiting",
        file: "a2a_interceptors.rs",
    },
    // ── Managed Agents ──
    ExampleMeta {
        id: "managed_agents_hello",
        name: "Managed Hello World",
        category: "Managed Agents",
        description: "Simplest managed agent — Gemini-hosted agent with automatic session management",
        file: "managed_agents_hello.rs",
    },
    ExampleMeta {
        id: "managed_agents_custom_tools",
        name: "Managed Custom Tools",
        category: "Managed Agents",
        description: "Managed agents with custom tool definitions — cloud-hosted function calling",
        file: "managed_agents_custom_tools.rs",
    },
    ExampleMeta {
        id: "managed_agents_files",
        name: "Managed File Upload",
        category: "Managed Agents",
        description: "Upload and process files with managed agents — document analysis pipeline",
        file: "managed_agents_files.rs",
    },
    ExampleMeta {
        id: "managed_agents_memory",
        name: "Managed Memory",
        category: "Managed Agents",
        description: "Persistent memory across sessions with managed agents — cross-conversation recall",
        file: "managed_agents_memory.rs",
    },
    ExampleMeta {
        id: "managed_agents_multiagent",
        name: "Managed Multi-Agent",
        category: "Managed Agents",
        description: "Multi-agent coordinator with managed agents — task delegation and synthesis",
        file: "managed_agents_multiagent.rs",
    },
    ExampleMeta {
        id: "managed_runtime_hello",
        name: "Managed Runtime",
        category: "Managed Agents",
        description: "Managed agent runtime — hello world smoke test with streaming",
        file: "managed_runtime_hello.rs",
    },
    // ── OpenAI Responses API ──
    ExampleMeta {
        id: "openai_responses",
        name: "Responses API",
        category: "OpenAI Responses",
        description: "OpenAI Responses API with reasoning, tool use, and streaming",
        file: "openai_responses.rs",
    },
    ExampleMeta {
        id: "openai_conversations",
        name: "Conversations API",
        category: "OpenAI Responses",
        description: "Multi-turn conversations with server-managed state via conversation_id",
        file: "openai_conversations.rs",
    },
    ExampleMeta {
        id: "openai_background",
        name: "Background Mode",
        category: "OpenAI Responses",
        description: "Fire-and-forget async tasks — poll for completion via response_id",
        file: "openai_background.rs",
    },
    ExampleMeta {
        id: "openai_deep_research",
        name: "Deep Research",
        category: "OpenAI Responses",
        description: "Multi-step research with web search, citations, and synthesis",
        file: "openai_deep_research.rs",
    },
    ExampleMeta {
        id: "openai_open_responses",
        name: "Open Responses",
        category: "OpenAI Responses",
        description: "Open-ended responses with configurable output formats",
        file: "openai_open_responses.rs",
    },
    ExampleMeta {
        id: "openai_builtin_tools",
        name: "OpenAI Built-In Tools",
        category: "OpenAI Responses",
        description: "Code interpreter, file search, and web search hosted tools",
        file: "openai_builtin_tools.rs",
    },
    ExampleMeta {
        id: "openai_server_tools",
        name: "OpenAI Server Tools",
        category: "OpenAI Responses",
        description: "Server-side tool execution — live agentic example matrix",
        file: "openai_server_tools.rs",
    },
    // ── Gemini Features ──
    ExampleMeta {
        id: "gemini3_builtin_tools",
        name: "Gemini Native Tools",
        category: "Gemini Features",
        description: "Gemini native tools — live agentic example matrix with grounding",
        file: "gemini3_builtin_tools.rs",
    },
    ExampleMeta {
        id: "gemini_interactions_agent",
        name: "Gemini Interactions",
        category: "Gemini Features",
        description: "Gemini Interactions API — runtime agent with streaming responses",
        file: "gemini_interactions_agent.rs",
    },
    ExampleMeta {
        id: "gemini_managed_agents",
        name: "Gemini Managed Agents",
        category: "Gemini Features",
        description: "Gemini managed agents — practical examples with streaming",
        file: "gemini_managed_agents.rs",
    },
    ExampleMeta {
        id: "multimodal_function_response",
        name: "Multimodal Tool Responses",
        category: "Gemini Features",
        description: "Return images, audio, and files from function tools to Gemini models",
        file: "multimodal_function_response.rs",
    },
    // ── Graph v2 ──
    ExampleMeta {
        id: "deferred_nodes",
        name: "Deferred Nodes",
        category: "Graph v2",
        description: "Lazy-evaluated graph nodes — defer expensive computation until needed",
        file: "deferred_nodes.rs",
    },
    ExampleMeta {
        id: "delta_checkpoints",
        name: "Delta Checkpoints",
        category: "Graph v2",
        description: "Incremental state checkpointing — only persist changed fields",
        file: "delta_checkpoints.rs",
    },
    ExampleMeta {
        id: "node_caching",
        name: "Node Caching",
        category: "Graph v2",
        description: "Cache deterministic node outputs — skip re-computation on replay",
        file: "node_caching.rs",
    },
    ExampleMeta {
        id: "node_timeouts",
        name: "Node Timeouts",
        category: "Graph v2",
        description: "Per-node execution timeouts with graceful fallback handling",
        file: "node_timeouts.rs",
    },
    ExampleMeta {
        id: "time_travel",
        name: "Time Travel",
        category: "Graph v2",
        description: "Replay and branch graph execution from any checkpoint",
        file: "time_travel.rs",
    },
    ExampleMeta {
        id: "functional_workflow",
        name: "Functional Workflow",
        category: "Graph v2",
        description: "Composable pure-function nodes with typed inputs and outputs",
        file: "functional_workflow.rs",
    },
    // ── Enterprise ──
    ExampleMeta {
        id: "server_builder",
        name: "Server Builder",
        category: "Enterprise",
        description: "Fluent ServerBuilder API — configure routes, middleware, and deploy",
        file: "server_builder.rs",
    },
    ExampleMeta {
        id: "secret_provider",
        name: "Secret Provider",
        category: "Enterprise",
        description: "Pluggable secret management — inject API keys at runtime without .env",
        file: "secret_provider.rs",
    },
    ExampleMeta {
        id: "yaml_agent",
        name: "YAML Agent",
        category: "Enterprise",
        description: "Define agents in YAML — env interpolation, plugins, session backends",
        file: "yaml_agent.rs",
    },
    ExampleMeta {
        id: "agent_registry",
        name: "Agent Registry",
        category: "Enterprise",
        description: "Discoverable agent registry — register, lookup, and route to agents by name",
        file: "agent_registry.rs",
    },
    // ── Production Patterns ──
    ExampleMeta {
        id: "context_compaction",
        name: "Context Compaction",
        category: "Production",
        description: "Sliding-window event summarization — keep context within token limits",
        file: "context_compaction.rs",
    },
    ExampleMeta {
        id: "intra_compaction",
        name: "Intra-Invocation Compaction",
        category: "Production",
        description: "Mid-conversation summarization when token threshold is exceeded",
        file: "intra_compaction.rs",
    },
    ExampleMeta {
        id: "tool_concurrency",
        name: "Tool Concurrency",
        category: "Production",
        description: "ToolConcurrencyConfig — per-tool limits, backpressure, and priority",
        file: "tool_concurrency.rs",
    },
    ExampleMeta {
        id: "background_runs",
        name: "Background Runs",
        category: "Production",
        description: "Fire-and-forget agent execution — poll status, retrieve results later",
        file: "background_runs.rs",
    },
    ExampleMeta {
        id: "cron_scheduling",
        name: "Cron Scheduling",
        category: "Production",
        description: "Schedule agent runs with cron expressions — periodic tasks and monitoring",
        file: "cron_scheduling.rs",
    },
    ExampleMeta {
        id: "ambient_cron_agent",
        name: "Ambient Cron Agent",
        category: "Production",
        description: "Always-on background agent with scheduled tasks and event triggers",
        file: "ambient_cron_agent.rs",
    },
    ExampleMeta {
        id: "output_schema_agent",
        name: "Output Schema Agent",
        category: "Production",
        description: "Force structured JSON output matching a schema — all providers",
        file: "output_schema_agent.rs",
    },
    ExampleMeta {
        id: "prompt_optimizer",
        name: "Prompt Optimizer",
        category: "Production",
        description: "Automated prompt tuning — test variations, measure quality, pick best",
        file: "prompt_optimizer.rs",
    },
    ExampleMeta {
        id: "user_personas",
        name: "User Personas",
        category: "Production",
        description: "Dynamic persona switching — adapt agent behavior per user profile",
        file: "user_personas.rs",
    },
    // ── Anthropic Native ──
    ExampleMeta {
        id: "anthropic_server_tools",
        name: "Anthropic Server Tools",
        category: "Anthropic Native",
        description: "Anthropic native tools — live agentic example matrix with server-side execution",
        file: "anthropic_server_tools.rs",
    },
    // ── Eval ──
    ExampleMeta {
        id: "eval_showcase",
        name: "Eval Showcase",
        category: "Eval",
        description: "Full eval framework — test cases, metrics, scoring, and reporting",
        file: "eval_showcase.rs",
    },
    // ── Sandbox ──
    ExampleMeta {
        id: "sandbox_agent",
        name: "Sandbox Agent",
        category: "Sandbox",
        description: "Isolated code execution — agent writes and runs code in a sandboxed environment",
        file: "sandbox_agent.rs",
    },
    // ── Skills ──
    ExampleMeta {
        id: "skill_memory_improvements",
        name: "Skill Memory",
        category: "Skills",
        description: "Enhanced skill memory — persistent skill state across sessions",
        file: "skill_memory_improvements.rs",
    },
    ExampleMeta {
        id: "skills_multilingual",
        name: "Multilingual Skills",
        category: "Skills",
        description: "Multilingual skill matching — discover and inject skills across languages",
        file: "skills_multilingual.rs",
    },
    // ── DeepSeek ──
    ExampleMeta {
        id: "deepseek_v4",
        name: "DeepSeek V4 Full",
        category: "DeepSeek",
        description: "All 7 DeepSeek V4 features — Flash, Pro, thinking, tools, multi-turn, legacy compat",
        file: "deepseek_v4.rs",
    },
    // ── Competitive Ergonomics ──
    ExampleMeta {
        id: "competitive_ergonomics",
        name: "Ergonomic APIs",
        category: "Competitive",
        description: "Zero-config ergonomics — provider_from_env(), adk::run(), encrypted sessions",
        file: "competitive_ergonomics.rs",
    },
];

pub fn load_examples() -> Vec<Example> {
    let examples_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("examples");

    REGISTRY
        .iter()
        .filter_map(|meta| {
            let path = examples_dir.join(meta.file);
            let code = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| format!("// Error loading {}: {}", meta.file, e));
            Some(Example {
                id: meta.id.to_string(),
                name: meta.name.to_string(),
                category: meta.category.to_string(),
                description: meta.description.to_string(),
                code,
            })
        })
        .collect()
}
