//! Output Schema Agent Example
//!
//! Demonstrates **Output Schema enforcement** on an LlmAgent with Gemini.
//! The agent is configured with `output_type::<T>()` so it produces structured
//! JSON matching a Rust type, and we use `extract_typed::<T>()` to deserialize
//! the response into a strongly-typed struct.
//!
//! Scenarios:
//!   1. MovieReview — ask for a structured movie review
//!   2. Recipe — ask for a structured recipe
//!
//! Requires `GOOGLE_API_KEY` at runtime. Without it the example prints
//! instructions and exits gracefully.
//!
//! # Usage
//!
//! ```bash
//! export GOOGLE_API_KEY=your-key-here
//! cargo run --manifest-path examples/output_schema_agent/Cargo.toml
//! ```

use std::collections::HashMap;
use std::sync::Arc;

use adk_agent::{LlmAgentBuilder, extract_typed};
use adk_core::{Agent, Content, Event, RunConfig, SessionId, StreamingMode, UserId};
use adk_model::GeminiModel;
use adk_runner::Runner;
use adk_session::{CreateRequest, InMemorySessionService, SessionService};
use futures::StreamExt;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use tracing_subscriber::EnvFilter;

// ─── Output Schema Types ─────────────────────────────────────────────────────

/// A structured movie review with rating, summary, pros, and cons.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
struct MovieReview {
    /// Title of the movie being reviewed.
    title: String,
    /// Rating out of 10 (1-10).
    rating: u8,
    /// A brief summary of the movie (1-3 sentences).
    summary: String,
    /// List of positive aspects of the movie.
    pros: Vec<String>,
    /// List of negative aspects or criticisms.
    cons: Vec<String>,
}

/// A structured recipe with ingredients, steps, and timing.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
struct Recipe {
    /// Name of the dish.
    name: String,
    /// List of ingredients with quantities.
    ingredients: Vec<String>,
    /// Step-by-step cooking instructions.
    steps: Vec<String>,
    /// Estimated preparation time in minutes.
    prep_time_minutes: u32,
    /// Estimated cooking time in minutes.
    cook_time_minutes: u32,
    /// Number of servings this recipe yields.
    servings: u32,
}

// ─── Constants ───────────────────────────────────────────────────────────────

const APP_NAME: &str = "output-schema-agent";
const USER_ID: &str = "demo-user";
const MODEL_NAME: &str = "gemini-2.5-flash";

// ─── Schema Helpers ──────────────────────────────────────────────────────────

/// Strips fields that the Gemini API rejects from a JSON Schema value.
/// The API does not accept `$schema`, `title` at the root, or certain
/// metadata fields generated by `schemars`.
fn clean_schema_for_gemini(schema: &mut serde_json::Value) {
    if let Some(obj) = schema.as_object_mut() {
        obj.remove("$schema");
        obj.remove("title");
        // Recursively clean nested schemas
        if let Some(props) = obj.get_mut("properties") {
            if let Some(props_obj) = props.as_object_mut() {
                for value in props_obj.values_mut() {
                    clean_schema_for_gemini(value);
                }
            }
        }
        if let Some(items) = obj.get_mut("items") {
            clean_schema_for_gemini(items);
        }
    }
}

/// Generate a Gemini-compatible JSON schema from a type implementing `JsonSchema`.
fn gemini_schema<T: JsonSchema>() -> serde_json::Value {
    let schema = schemars::schema_for!(T);
    let mut value = serde_json::to_value(schema).expect("schema serialization cannot fail");
    clean_schema_for_gemini(&mut value);
    value
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

fn api_key() -> Option<String> {
    std::env::var("GOOGLE_API_KEY")
        .ok()
        .or_else(|| std::env::var("GEMINI_API_KEY").ok())
        .filter(|key| !key.trim().is_empty())
}

fn print_banner() {
    println!("╔══════════════════════════════════════════════════════════════╗");
    println!("║        Output Schema Agent — Structured LLM Responses       ║");
    println!("║                                                              ║");
    println!("║  Demonstrates: output_type::<T>(), extract_typed::<T>()      ║");
    println!("║  Model: Gemini 2.5 Flash                                     ║");
    println!("╚══════════════════════════════════════════════════════════════╝");
    println!();
}

fn print_section(title: &str) {
    println!("\n┌─────────────────────────────────────────────────────────────┐");
    println!("│ {title:<60}│");
    println!("└─────────────────────────────────────────────────────────────┘");
}

/// Builds a Runner for the given agent and creates a session.
/// Uses `StreamingMode::None` so each LLM response arrives as a single
/// complete event (required for `extract_typed` to work correctly).
async fn make_runner(agent: Arc<dyn Agent>, session_id: &str) -> anyhow::Result<Runner> {
    let sessions: Arc<dyn SessionService> = Arc::new(InMemorySessionService::new());
    sessions
        .create(CreateRequest {
            app_name: APP_NAME.into(),
            user_id: USER_ID.into(),
            session_id: Some(session_id.into()),
            state: HashMap::new(),
        })
        .await?;

    let run_config = RunConfig::builder()
        .streaming_mode(StreamingMode::None)
        .build();

    Ok(Runner::builder()
        .app_name(APP_NAME)
        .agent(agent)
        .session_service(sessions)
        .run_config(run_config)
        .build()?)
}

/// Runs a single turn and collects all events.
async fn run_and_collect(
    runner: &Runner,
    session_id: &str,
    prompt: &str,
) -> anyhow::Result<Vec<Event>> {
    println!("  👤 Prompt: \"{prompt}\"");
    println!("  ⏳ Waiting for structured response...\n");

    let mut stream = runner
        .run(
            UserId::new(USER_ID)?,
            SessionId::new(session_id)?,
            Content::new("user").with_text(prompt),
        )
        .await?;

    let mut events = Vec::new();
    while let Some(event) = stream.next().await {
        events.push(event?);
    }

    Ok(events)
}

// ─── Scenario 1: Movie Review ────────────────────────────────────────────────

async fn scenario_movie_review(api_key: &str) -> anyhow::Result<()> {
    print_section("Scenario 1: Structured Movie Review");

    println!("  📋 Schema: MovieReview {{ title, rating, summary, pros, cons }}");
    println!();

    let model = Arc::new(GeminiModel::new(api_key, MODEL_NAME)?);

    let agent = Arc::new(
        LlmAgentBuilder::new("movie-reviewer")
            .model(model)
            .instruction(
                "You are a professional movie critic. When asked to review a movie, \
                 provide a structured review with a title, rating (1-10), brief summary, \
                 list of pros, and list of cons. Be concise but insightful.",
            )
            .output_schema(gemini_schema::<MovieReview>())
            .build()?,
    );

    let runner = make_runner(agent, "movie-review").await?;
    let events =
        run_and_collect(&runner, "movie-review", "Write a review of the movie Inception").await?;

    // Extract typed response
    match extract_typed::<MovieReview>(&events) {
        Ok(review) => {
            println!("  ✅ Successfully extracted MovieReview:");
            println!("  ───────────────────────────────────────");
            println!("  🎬 Title:   {}", review.title);
            println!("  ⭐ Rating:  {}/10", review.rating);
            println!("  📝 Summary: {}", review.summary);
            println!("  👍 Pros:");
            for pro in &review.pros {
                println!("     • {pro}");
            }
            println!("  👎 Cons:");
            for con in &review.cons {
                println!("     • {con}");
            }
            println!();
        }
        Err(e) => {
            println!("  ❌ Failed to extract typed response: {e}");
            println!("  (The model may not have returned valid JSON for the schema)");
            println!();
        }
    }

    Ok(())
}

// ─── Scenario 2: Recipe ──────────────────────────────────────────────────────

async fn scenario_recipe(api_key: &str) -> anyhow::Result<()> {
    print_section("Scenario 2: Structured Recipe");

    println!("  📋 Schema: Recipe {{ name, ingredients, steps, prep_time_minutes, ... }}");
    println!();

    let model = Arc::new(GeminiModel::new(api_key, MODEL_NAME)?);

    let agent = Arc::new(
        LlmAgentBuilder::new("recipe-generator")
            .model(model)
            .instruction(
                "You are a professional chef. When asked for a recipe, provide structured \
                 output with the dish name, a list of ingredients with quantities, \
                 step-by-step instructions, preparation time, cooking time, and number \
                 of servings. Be precise with measurements.",
            )
            .output_schema(gemini_schema::<Recipe>())
            .build()?,
    );

    let runner = make_runner(agent, "recipe").await?;
    let events = run_and_collect(
        &runner,
        "recipe",
        "Give me a recipe for chocolate chip cookies",
    )
    .await?;

    // Extract typed response
    match extract_typed::<Recipe>(&events) {
        Ok(recipe) => {
            println!("  ✅ Successfully extracted Recipe:");
            println!("  ───────────────────────────────────────");
            println!("  🍽️  Name:      {}", recipe.name);
            println!("  ⏱️  Prep time: {} minutes", recipe.prep_time_minutes);
            println!("  🔥 Cook time: {} minutes", recipe.cook_time_minutes);
            println!("  🍽️  Servings:  {}", recipe.servings);
            println!();
            println!("  📦 Ingredients:");
            for ingredient in &recipe.ingredients {
                println!("     • {ingredient}");
            }
            println!();
            println!("  📖 Steps:");
            for (i, step) in recipe.steps.iter().enumerate() {
                println!("     {}. {step}", i + 1);
            }
            println!();
        }
        Err(e) => {
            println!("  ❌ Failed to extract typed response: {e}");
            println!("  (The model may not have returned valid JSON for the schema)");
            println!();
        }
    }

    Ok(())
}

// ─── Entry Point ─────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    dotenvy::dotenv().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("warn")),
        )
        .init();

    print_banner();

    let Some(key) = api_key() else {
        println!("⚠️  No API key found.");
        println!();
        println!("This example requires a Google API key to invoke Gemini.");
        println!("Set one of the following environment variables:");
        println!();
        println!("  export GOOGLE_API_KEY=your-key-here");
        println!("  export GEMINI_API_KEY=your-key-here");
        println!();
        println!("Then re-run:");
        println!("  cargo run --manifest-path examples/output_schema_agent/Cargo.toml");
        return Ok(());
    };

    println!("🔑 API key detected. Running with model: {MODEL_NAME}");

    scenario_movie_review(&key).await?;
    scenario_recipe(&key).await?;

    print_section("Done");
    println!("  All scenarios completed successfully.");
    println!("  Output schemas ensure the LLM produces valid, parseable JSON.");
    println!();

    Ok(())
}
